BUG: Use correct error message for arcive delete.

diff --git a/bin/archive b/bin/archive
--- a/bin/archive
+++ b/bin/archive
@@ -268,7 +268,7 @@ elif [[ $action == "delete" ]]; then
 	shift $((${OPTIND:-1}-1))
 
 	if [[ -z $opt_key ]]; then
-		echo "ABORT: Edit what archive? Missing -u ..." >&2
+		echo "ABORT: Remove what archive? Missing -u ..." >&2
 		show_help
 		exit 1
 	fi
