FEATURE: Support server/start to start a offline server.

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -50,6 +50,10 @@ show_help () {
 				  Optional string with status types to show.
 				  Must have a server to show status about.
 
+		start	  Power up a server
+				  (-b will boot to bios screen, not available on all platforms)
+				  Must have a server key provided.
+
 		arguments	 List acceptable values to arguments
 					   Can use a server key as input, useful in
 					   case of edits.
@@ -178,6 +182,13 @@ status () {
 
 	# TODO need to add some formatting for this.
 	curl-json "{\"serverid\":\"$serverKey\"${statusType:-}}" server/status "$project:$apikey" | jq -r #'.response.status.text'
+}
+
+server_start() {
+	local serverKey=$1
+	local biosStart="\"bios\":\"$2\""
+
+	curl-json "{\"serverid\":\"$serverKey\",$biosStart}" server/start "$project:$apikey" | jq -r '.response.status.text'
 }
 
 
@@ -501,6 +512,33 @@ elif [[ $action == "status" ]]; then
 	exportSettings "$settings"
 
 	status "$key" "${types:-}"
+
+elif [[ $action == "start" ]]; then
+	while getopts "bc:" option; do
+		case "$option" in
+			b) opt_bios=yes ;;
+			c)
+				if [[ -f $OPTARG ]]; then
+					settings=$OPTARG
+				fi
+				;;
+			*) show_help ; exit 1 ;;
+		esac
+	done
+
+	shift $((${OPTIND:-1}-1))
+	key=$1
+
+	if [[ -z $key ]]; then
+		echo "ABORT: Must specify key of server to start."
+		echo "eg. wps123456, kvm12345..."
+		exit 1
+	fi
+
+	settings=$(gleshys-discover-settings "$settings")
+	exportSettings "$settings"
+
+	server_start "$key" "${opt_bios:-no}"
 
 else
 	show_help
